--App audit trail
  CREATE TABLE "APP_AUDIT_LOG" (	
    "SEQ_NO" NUMBER,
    "USER_LOGIN_ACCOUNT" VARCHAR2(20 BYTE), 
	"SOURCE_IP" VARCHAR2(25 BYTE), 
	"DATE_TIME" VARCHAR2(20 BYTE), 
	"APPLICATION_NAME" VARCHAR2(20 BYTE), 
	"ACTION_TYPE" VARCHAR2(2 BYTE), 
	"PROGRAM_NAME" VARCHAR2(100 BYTE), 
	"ACCESS_OBJECT_TYPE" VARCHAR2(2 BYTE), 
	"KEY_FIELD" CHAR(8 BYTE), 
	"COMPANY_TYPE" VARCHAR2(2 BYTE), 
	"BRANCH_NO" CHAR(5 BYTE), 
	"EMPLOYEE_ID" CHAR(5 BYTE), 
	"ROLE" VARCHAR2(50 BYTE), 
	"RECORD_COUNT" NUMBER(*,0), 
	"DATA_ACCESS" VARCHAR2(8 BYTE), 
	"OLD_VALUE" VARCHAR2(200 BYTE), 
	"NEW_VALUE" VARCHAR2(200 BYTE), 
	"SQL_STATEMENT" VARCHAR2(1000 BYTE), 
	 PRIMARY KEY ("SEQ_NO");

  CREATE SEQUENCE  "CRM_APP_AUDIT_TRAIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
	 
--User audit trail	
  CREATE TABLE "USER_AUDIT_LOG" (	
    "SEQ_NO" NUMBER, 
    "USER_LOGIN_ACCOUNT" VARCHAR2(20 BYTE), 
	"SOURCE_IP" VARCHAR2(25 BYTE), 
	"ACTION" VARCHAR2(5 BYTE), 
	"DATE_TIME" VARCHAR2(20 BYTE), 
	"AP_ID" VARCHAR2(20 BYTE), 
	"LOGIN_SERVER_NAME" VARCHAR2(16 BYTE), 
	"DATA_ACCESS" VARCHAR2(8 BYTE), 
	 PRIMARY KEY ("SEQ_NO");
	 
  CREATE SEQUENCE  "CRM_USER_AUDIT_TRAIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;






-- drop table APP_AUDIT_LOG;
-- drop table USER_AUDIT_LOG;
-- drop sequence CRM_APP_AUDIT_TRAIL_SEQ;
-- drop sequence CRM_USER_AUDIT_TRAIL_SEQ;