export default {
  PLOAN: "PLOAN",
  HLOAN: "HLOAN",
  CPIN: "CPIN",
  PAYINS: "PAYINS",
  ILOCA: "ILOCA",
  CDU: "CDU",
  PLOAN_LABEL: "小信",
  HLOAN_LABEL: "房貸",
  CPIN_LABEL: "CPIN",
  PAYINS_LABEL: "帳單分期",
  ILOCA_LABEL: "分期預借現金",
  CDU_LABEL: "客戶資料更新",
  RIGHT_DATA: "資料正確",
  WRONG_DATA: "待更新",
  NO_BANKING_DATA: "非本行存戶",
  NO_CREDIT_CARD_DATA: "非本行卡友",
  INTERESTED: "有興趣",
  NO_NEED: "無需求",
  NOT_SUITABLE: "不適合開口",
  ISSUE_A_LIST: "開單",
  ONLINE_REFERRAL: "線上轉介",
  REFERRAL: "轉介件",
  CUSTOMER_ASK: "自來件"
};
