//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.17 at 04:27:27 PM SGT 
//


package com.cathay.api.rop.req;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="XMLSTRING" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetODSData", propOrder = {
    "xmlstring"
})
@XmlRootElement(name = "ods:GetODSData")
@XmlSeeAlso({GetODSXmlString.class})
public class GetODSData {

    @XmlElement(name = "ods:XMLSTRING")
    protected String xmlstring;

    /**
     * Gets the value of the xmlstring property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXMLSTRING() {
        return xmlstring;
    }

    /**
     * Sets the value of the xmlstring property.
     * 
     * @param object
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXMLSTRING(String object) {
        this.xmlstring = object;
    }

}
