export default {
  SUCCESS_CODE: "0000",
  NO_DATA_CODE: "1001",
  ERROR_CODE: "1111",
  RETRY_INTERVAL: 5000,
  SUCCESS_STATUS: 200,
  MODAL_LOADING: 3000,
  SERVICE_UNAVAILABLE: "暫停服務",
  RETRY: "重試",
  GIFT_DETAILS: "GIFT-DETAILS",
  ACTIVITIES: "ACTIVITIES"
};
