//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.17 at 04:27:27 PM SGT 
//


package com.cathay.api.ods.rop;

import javax.xml.bind.annotation.XmlRegistry;

import com.cathay.api.rop.req.GetODSData;
import com.cathay.api.rop.resp.GetODSDataResponse;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tw.com.cathaybk.odswebservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * 
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {
	
    public GetODSData createGetODSData() {
        return new GetODSData();
    }

    /**
     * Create an instance of {@link GetODSDataResponse }
     * 
     */
    public GetODSDataResponse createGetODSDataResponse() {
        return new GetODSDataResponse();
    }

}
