//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.17 at 04:27:27 PM SGT 
//


package tw.com.cathaybk.odswebservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tw.com.cathaybk.odswebservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tw.com.cathaybk.odswebservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetODSData }
     * 
     */
    public GetODSData createGetODSData() {
        return new GetODSData();
    }

    /**
     * Create an instance of {@link GetODSDataResponse }
     * 
     */
    public GetODSDataResponse createGetODSDataResponse() {
        return new GetODSDataResponse();
    }

    /**
     * Create an instance of {@link OnlineStartBatch }
     * 
     */
    public OnlineStartBatch createOnlineStartBatch() {
        return new OnlineStartBatch();
    }

    /**
     * Create an instance of {@link OnlineStartBatchResponse }
     * 
     */
    public OnlineStartBatchResponse createOnlineStartBatchResponse() {
        return new OnlineStartBatchResponse();
    }

    /**
     * Create an instance of {@link GetConnection }
     * 
     */
    public GetConnection createGetConnection() {
        return new GetConnection();
    }

    /**
     * Create an instance of {@link GetConnectionResponse }
     * 
     */
    public GetConnectionResponse createGetConnectionResponse() {
        return new GetConnectionResponse();
    }

    /**
     * Create an instance of {@link CheckService }
     * 
     */
    public CheckService createCheckService() {
        return new CheckService();
    }

    /**
     * Create an instance of {@link CheckServiceResponse }
     * 
     */
    public CheckServiceResponse createCheckServiceResponse() {
        return new CheckServiceResponse();
    }

    /**
     * Create an instance of {@link GetSQLData }
     * 
     */
    public GetSQLData createGetSQLData() {
        return new GetSQLData();
    }

    /**
     * Create an instance of {@link GetSQLDataResponse }
     * 
     */
    public GetSQLDataResponse createGetSQLDataResponse() {
        return new GetSQLDataResponse();
    }

    /**
     * Create an instance of {@link GetTeradataMacData }
     * 
     */
    public GetTeradataMacData createGetTeradataMacData() {
        return new GetTeradataMacData();
    }

    /**
     * Create an instance of {@link GetTeradataMacDataResponse }
     * 
     */
    public GetTeradataMacDataResponse createGetTeradataMacDataResponse() {
        return new GetTeradataMacDataResponse();
    }

}
